### ISSUE TITLE
How to exclude specific types of files from the checker?

### ISSUE THREAD

**Issue by RevoluPowered** [HL7/bidi-checker-action#19]
Hi, 

I am setting this up for Godot and wondering if you have a method implemented for ignoring specific file patterns?

We have unicode translation files in our project which get triggered so I was testing this out and hit the errors with our translation files and some .png assets.

I would like to ignore some files by default.

Here is an example :)
https://github.com/godotengine/godot/runs/4557890721?check_suite_focus=true

Thanks,
Gordon

**Comment by dotasek** [comment]
Hi Gordon, apologies for the delay, I haven't had much time to implement any improvements. 

v1.7 now contains this feature, which is a simple regex passed as the environment variable IGNORE

You can see an example of this in use here:

https://github.com/HL7/fhir-ig-publisher/blob/master/.github/workflows/bidi-checker.yml
